<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WIM</AssemblyName>
    <RootNamespace>WimFluent</RootNamespace>
    <ApplicationIcon>assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\app.ico" />
  </ItemGroup>

</Project>
